apiVersion: v1
kind: PersistentVolume
metadata:
  name: configurations-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  claimRef:
    namespace: default
    name: configurations-pv-claim
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: projects/skilful-scarab-324909/zones/europe-west1-b/disks/impaqt-configurations
    fsType: ext4
    readOnly: true
