apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-swagger-ui-deployment
  labels:
    app: container-swagger-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-swagger-ui
  template:
    metadata:
      labels:
        app: container-swagger-ui
    spec:
      containers:
      - name: impaqt-container-swaggerui
        image: tomaszluczynski/impaqt-container-swagger-ui:2.11-SNAPSHOT
        #command: [ "/bin/bash", "-c", "--" ]
        #args: [ "while true; do sleep 30; done;" ]
        imagePullPolicy: "Always"
        resources:
          requests:
            memory: "1024Mi"
          limits:
            memory: "2048Mi"
        ports:
        - containerPort: 8000
          name: webserver
        env:
          - name: SERVER_PORT
            value: "8000"
          - name: DATABASE_DDLAUTO
            value: "validate"
          - name: DATABASE_URL
            valueFrom:
              configMapKeyRef:
                name: maria-configmap
                key: url
          - name: DATABASE_USERNAME
            valueFrom:
              configMapKeyRef:
                name: maria-configmap
                key: username
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: maria-secret
                key: password
        volumeMounts:
          - name: config-volume
            mountPath: /opt/swissquant/config
      volumes:
        - name: config-volume
          projected:
            sources:
              - configMap:
                  name: container-swagger-ui-configmap
              - configMap:
                  name: users-configmap
      imagePullSecrets:
      - name: regcred

