apiVersion: v1
kind: ConfigMap
metadata:
  name: container-wapi-risk-configmap
data:
  container.conf: |
    cache.type = REPLICATED
    server {
      ssl {
        enabled = false
      }
    }

    security {
      authentication {
        enabled = true
        type = HTPASSWD
        legacyMethod = BASIC
      }

      htpasswd {
        file = "/opt/swissquant/config/admin.htpasswd"
      }
    }

    distributed {
      broker {
         broker-url = "failover:(tcp://activemq:61616)?randomize=false&priorityBackup=true"
      }
    }
