apiVersion: v1
kind: ConfigMap
metadata:
  name: container-gateway-configmap
data:
  application.yml: |
    spring.cloud:
        gateway:
          routes:
            - id: wapi_all
              uri: http://wapi-risk:8000
              predicates:
                - Path=/api/**
            - id: ui_swagger
              uri: http://swagger-ui:8000
              predicates:
                - Path=/swagger-ui/**
            - id: ui_swagger_yaml
              uri: http://swagger-ui:8000
              predicates:
                - Path=/wealth-api.yaml
            - id: ui_all
              uri: http://dataserver:8000
              predicates:
                - Path=/**
              filters:
                - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, ,
