apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-gateway-deployment
  labels:
    app: container-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-gateway
  template:
    metadata:
      labels:
        app: container-gateway
    spec:
      containers:
      - name: impaqt-container-gateway
        image: tomaszluczynski/impaqt-container-gateway:2.11-SNAPSHOT
        #command: [ "/bin/bash", "-c", "--" ]
        #args: [ "while true; do sleep 30; done;" ]
        imagePullPolicy: "Always"
        resources:
          requests:
            memory: "1024Mi"
          limits:
            memory: "2048Mi"
        ports:
        - containerPort: 8000
          name: webserver
        env:
          - name: SERVER_PORT
            value: "8000"
          - name: NETTY_HTTP_SERVER_ACCESSLOGENABLED
            value: "true"
        volumeMounts:
          - name: config-volume
            mountPath: /opt/swissquant/config

      volumes:
        - name: config-volume
          projected:
            sources:
              - configMap:
                  name: container-gateway-configmap
      imagePullSecrets:
      - name: regcred

