apiVersion: v1
kind: ConfigMap
metadata:
  name: container-gateway-configmap
data:
  application.yml: |
    spring.cloud:
        gateway:
          routes:
            - id: wapi_all
              uri: http://wapi-risk:8000
              predicates:
                - Path=/api/**
            - id: ui_swagger
              uri: http://swagger-ui:8000
              predicates:
                - Path=/swagger-ui/**
            - id: ui_swagger_yaml
              uri: http://swagger-ui:8000
              predicates:
                - Path=/wealth-api.yaml
            - id: ui_all
              uri: http://dataserver:8000
              predicates:
                - Path=/**
              filters:
                - RewriteLocationResponseHeader=AS_IN_REQUEST, Location, ,
  logback.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>

        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <encoder>
                <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
            </encoder>
        </appender>

        <appender name="async" class="ch.qos.logback.classic.AsyncAppender">
            <appender-ref ref="STDOUT" />
        </appender>

        <logger name="reactor.netty.http.server.AccessLog" level="INFO" />

        <root level="INFO">
            <appender-ref ref="STDOUT" />
        </root>
    </configuration>
