apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - image: mariadb:10.6.4
        name: mariadb
        resources:
          requests:
            memory: "1024Mi"
          limits:
            memory: "2048Mi"
        env:
          # Use secret in real usage
        - name: MARIADB_ROOT_PASSWORD
          value: test123
        - name: MARIADB_DATABASE
          value: impaqt
        ports:
        - containerPort: 3306
          name: mariadb
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
