apiVersion: v1
kind: ConfigMap
metadata:
  name: users-configmap
data:
  users.csv: |
    1,admin,admin,de,ADMINMODIFY
  admin.htpasswd: |
    # this line shouldn't contain a user
    admin:$apr1$HAFOBbgp$Zwl4D9FrRUGLgUeFgWgWJ1